; Ability constants
	const_def
	const NO_ABILITY   ; 00
	const OVERGROW     ; 01x
	const BLAZE        ; 02x
	const TORRENT      ; 03x
	const THICK_FAT    ; 04x
	const RECKLESS     ; 05
	const SOLAR_POWER  ; 06
	const DAMP         ; 07
	const SWIFT_SWIM   ; 08x
	const KEEN_EYE     ; 09
	const SKILL_LINK   ; 0a
	const SHEER_FORCE  ; 0b
	const VITAL_SPIRIT ; 0c
	const RUN_AWAY     ; 0d
	const INTIMIDATE   ; 0ex
	const SCRAPPY      ; 0f
	const LIMBER       ; 10
	const UNBURDEN     ; 11
	const PRANKSTER    ; 12x
	const STURDY       ; 13
	const WEAK_ARMOR   ; 14
	const SAND_FORCE   ; 15x
	const SAND_RUSH    ; 16x
	const MOLD_BREAKER ; 17
	const GUTS         ; 18x
	const IRON_FIST    ; 19x
	const SWARM        ; 1ax
	const CHLOROPHYLL  ; 1bx
	const OVERCOAT     ; 1c
	const POISON_POINT ; 1dx
	const SPEED_BOOST  ; 1e
	const INFILTRATOR  ; 1f
	const TINTED_LENS  ; 20x
	const ADAPTABILITY ; 21
	const ROCK_HEAD    ; 22
	const RATTLED      ; 23x
	const MOXIE        ; 24
	const WATER_ABSORB ; 25x
	const LIQUID_OOZE  ; 26
	const WATER_VEIL   ; 27
	const SOLID_ROCK   ; 28x
	const SHADOW_TAG   ; 29
	const REFRIGERATE  ; 2ax
	const ROUGH_SKIN   ; 2bx
	const CUTE_CHARM   ; 2cx
	const TECHNICIAN   ; 2d
	const MAGIC_GUARD  ; 2e
	const REGENERATOR  ; 2f
	const LEVITATE     ; 30
	const ICE_BODY     ; 31
	const SNOW_WARNING ; 32x
	const DRIZZLE      ; 33x
	const DROUGHT      ; 34x
	const SANDSTREAM   ; 35x
	const SHELL_ARMOR  ; 36
	const NO_GUARD     ; 37
	const EFFECT_SPORE ; 38x
	const CURSED_BODY  ; 39x
	const MOODY        ; 3a
	const COMPOUNDEYES ; 3b
	const CLEAR_BODY   ; 3c
	const SYNCHRONIZE  ; 3d
	const ANALYTIC     ; 3ex
	const FLASH_FIRE   ; 3fx
	const FLAME_BODY   ; 40x
	const RIVALRY      ; 41
	const HYDRATION    ; 42
	const STICKY_HOLD  ; 43
	const STATIC       ; 44x
	const INNER_FOCUS  ; 45
	const PERISH_BODY  ; 46x
	const PRESSURE     ; 47
	const DEFIANT      ; 48
	const HUSTLE       ; 49
	const JUSTIFIED    ; 4a
	const VOLT_ABSORB  ; 4bx
	const MAGNET_PULL  ; 4c
	const OBLIVIOUS    ; 4d
	const OWN_TEMPO    ; 4e
	const STEADFAST    ; 4f
	const EARLY_BIRD   ; 50
	const TANGLED_FEET ; 51
	const GLUTTONY     ; 52
	const AFTERMATH    ; 53x
	const POISON_TOUCH ; 54x
	const HYPER_CUTTER ; 55
	const INSOMNIA     ; 56
	const SOUNDPROOF   ; 57x
	const LIGHTNINGROD ; 58x
	const BATTLE_ARMOR ; 59
	const CLOUD_NINE   ; 5a
	const NEUTRAL_GAS  ; 5b
	const STENCH       ; 5cx
	const SERENE_GRACE ; 5d
	const NATURAL_CURE ; 5e
	const SNIPER       ; 5f
	const FILTER       ; 60x
	const SCREEN_CLEAN ; 61x
	const SHARPNESS    ; 62x
	const MOTOR_DRIVE  ; 63x
	const ANGER_POINT  ; 64
	const QUICK_FEET   ; 65x
	const SNOW_CLOAK   ; 66
	const LEAF_GUARD   ; 67
	const TRACE        ; 68x
	const DOWNLOAD     ; 69x
	const SHED_SKIN    ; 6a
	const RAIN_DISH    ; 6b
	const MAGIC_BOUNCE ; 6cx
	const PICKUP       ; 6d
	const SHIELD_DUST  ; 6e
	const BIG_PECKS    ; 6f
	const UNNERVE      ; 70
	const SAND_VEIL    ; 71
	const UNAWARE      ; 72
	const COMPETITIVE  ; 73
	const FRISK        ; 74
	const DRY_SKIN     ; 75
	const WONDER_SKIN  ; 76
	const ARENA_TRAP   ; 77
	const ILLUMINATE   ; 78
	const IMPOSTER     ; 79
	const PIXILATE     ; 7ax
	const IMMUNITY     ; 7b
	const MARVEL_SCALE ; 7cx
	const MULTISCALE   ; 7d
	const SUPER_LUCK   ; 7e
	const HUGE_POWER   ; 7fx
	const SAP_SIPPER   ; 80x
	const ARMOR_TAIL   ; 81
	const POISON_HEAL  ; 82
	const CONTRARY     ; 83
	const PICKPOCKET   ; 84
	const BULLETPROOF  ; 85
	const MAGMA_ARMOR  ; 86
	const SUCTION_CUPS ; 87
	const HEAT_PROOF   ; 88x
	const MEGA_LAUNCHER ; 89
	const STRONG_JAW   ; 8ax
	const TOUGH_CLAWS  ; 8bx
	const SLOW_START   ; 8cx
	const DRAGONS_MAW  ; 8dx
	const TRANSISTOR   ; 8ex

NUM_ABILITIES EQU const_value + -1
