; Ability constants
	const_def
	const NO_ABILITY   ; 00
	const OVERGROW     ; 01x
	const BLAZE        ; 02x
	const TORRENT      ; 03x
	const THICK_FAT    ; 04x
	const RECKLESS     ; 05x
	const SOLAR_POWER  ; 06x
	const DAMP         ; 07x
	const SWIFT_SWIM   ; 08x
	const KEEN_EYE     ; 09x
	const SKILL_LINK   ; 0ax
	const SHEER_FORCE  ; 0bx
	const VITAL_SPIRIT ; 0cx
	const RUN_AWAY     ; 0dx
	const INTIMIDATE   ; 0ex
	const SCRAPPY      ; 0fx
	const LIMBER       ; 10x
	const UNBURDEN     ; 11x
	const PRANKSTER    ; 12x
	const STURDY       ; 13x
	const WEAK_ARMOR   ; 14x
	const SAND_FORCE   ; 15x
	const SAND_RUSH    ; 16x
	const MOLD_BREAKER ; 17
	const GUTS         ; 18x
	const IRON_FIST    ; 19x
	const SWARM        ; 1ax
	const CHLOROPHYLL  ; 1bx
	const OVERCOAT     ; 1cx
	const POISON_POINT ; 1dx
	const SPEED_BOOST  ; 1ex
	const INFILTRATOR  ; 1fx
	const TINTED_LENS  ; 20x
	const ADAPTABILITY ; 21x
	const ROCK_HEAD    ; 22x
	const RATTLED      ; 23x
	const MOXIE        ; 24
	const WATER_ABSORB ; 25x
	const LIQUID_OOZE  ; 26x
	const WATER_VEIL   ; 27x
	const SOLID_ROCK   ; 28x
	const SHADOW_TAG   ; 29x
	const REFRIGERATE  ; 2ax
	const ROUGH_SKIN   ; 2bx
	const CUTE_CHARM   ; 2cx
	const TECHNICIAN   ; 2dx
	const MAGIC_GUARD  ; 2ex
	const REGENERATOR  ; 2f
	const LEVITATE     ; 30x
	const ICE_BODY     ; 31x
	const SNOW_WARNING ; 32x
	const DRIZZLE      ; 33x
	const DROUGHT      ; 34x
	const SANDSTREAM   ; 35x
	const SHELL_ARMOR  ; 36x
	const NO_GUARD     ; 37x
	const EFFECT_SPORE ; 38x
	const CURSED_BODY  ; 39x
	const MOODY        ; 3a
	const COMPOUNDEYES ; 3bx
	const CLEAR_BODY   ; 3cx
	const SYNCHRONIZE  ; 3d
	const ANALYTIC     ; 3ex
	const FLASH_FIRE   ; 3fx
	const FLAME_BODY   ; 40x
	const RIVALRY      ; 41x
	const HYDRATION    ; 42x
	const STICKY_HOLD  ; 43
	const STATIC       ; 44x
	const INNER_FOCUS  ; 45x
	const PERISH_BODY  ; 46x
	const PRESSURE     ; 47
	const DEFIANT      ; 48x
	const HUSTLE       ; 49x
	const JUSTIFIED    ; 4ax
	const VOLT_ABSORB  ; 4bx
	const MAGNET_PULL  ; 4cx
	const OBLIVIOUS    ; 4dx
	const OWN_TEMPO    ; 4ex
	const STEADFAST    ; 4fx
	const EARLY_BIRD   ; 50x
	const TANGLED_FEET ; 51x
	const GLUTTONY     ; 52x
	const AFTERMATH    ; 53x
	const POISON_TOUCH ; 54x
	const HYPER_CUTTER ; 55x
	const INSOMNIA     ; 56x
	const SOUNDPROOF   ; 57x
	const LIGHTNINGROD ; 58x
	const BATTLE_ARMOR ; 59x
	const CLOUD_NINE   ; 5a
	const NEUTRAL_GAS  ; 5b
	const STENCH       ; 5cx
	const SERENE_GRACE ; 5dx
	const NATURAL_CURE ; 5e
	const SNIPER       ; 5fx
	const FILTER       ; 60x
	const SCREEN_CLEAN ; 61x
	const SHARPNESS    ; 62x
	const MOTOR_DRIVE  ; 63x
	const ANGER_POINT  ; 64x
	const QUICK_FEET   ; 65x
	const SNOW_CLOAK   ; 66x
	const LEAF_GUARD   ; 67x
	const TRACE        ; 68x
	const DOWNLOAD     ; 69x
	const SHED_SKIN    ; 6ax
	const RAIN_DISH    ; 6bx
	const MAGIC_BOUNCE ; 6cx
	const PICKUP       ; 6d
	const SHIELD_DUST  ; 6ex
	const BIG_PECKS    ; 6fx
	const UNNERVE      ; 70
	const SAND_VEIL    ; 71x
	const UNAWARE      ; 72
	const COMPETITIVE  ; 73x
	const FRISK        ; 74x
	const DRY_SKIN     ; 75x
	const WONDER_SKIN  ; 76x
	const ARENA_TRAP   ; 77x
	const ILLUMINATE   ; 78x
	const IMPOSTER     ; 79
	const PIXILATE     ; 7ax
	const IMMUNITY     ; 7bx
	const MARVEL_SCALE ; 7cx
	const MULTISCALE   ; 7dx
	const SUPER_LUCK   ; 7ex
	const HUGE_POWER   ; 7fx
	const SAP_SIPPER   ; 80x
	const ARMOR_TAIL   ; 81x
	const POISON_HEAL  ; 82x
	const CONTRARY     ; 83x
	const PICKPOCKET   ; 84x
	const BULLETPROOF  ; 85x
	const MAGMA_ARMOR  ; 86x
	const SUCTION_CUPS ; 87x
	const HEAT_PROOF   ; 88x
	const MEGA_LAUNCHER ; 89x
	const STRONG_JAW   ; 8ax
	const TOUGH_CLAWS  ; 8bx
	const SLOW_START   ; 8cx
	const DRAGONS_MAW  ; 8dx
	const TRANSISTOR   ; 8ex

NUM_ABILITIES EQU const_value + -1
