; Landmarks indexes (see data/maps/landmarks.asm)
	const_def

; Johto landmarks
	const SPECIAL_MAP       ; 00
	const BLACKTHORN_CITY   ; 01
	const DRAGONS_DEN       ; 02
	const ROUTE_45          ; 03
	const DARK_CAVE         ; 04
	const ICE_PATH          ; 05
	const ROUTE_44          ; 06
	const MAHOGANY_TOWN     ; 07
	const UNKNOWN           ; 08
	const ROUTE_43          ; 09
	const LAKE_OF_RAGE      ; 0a
	const INFANT_GROVE      ; 0b
	const ROUTE_42          ; 0c
	const MT_MORTAR         ; 0d
	const ECRUTEAK_CITY     ; 0e
	const BELLCHIME_PATH    ; 0f
	const TIN_TOWER         ; 10
	const BURNED_TOWER      ; 11
	const ROUTE_38          ; 12
	const ROUTE_39          ; 13
	const OLIVINE_CITY      ; 14
	const LIGHTHOUSE        ; 15
	const BATTLE_TOWER      ; 16
	const ROUTE_40          ; 17
	const WHIRL_ISLANDS     ; 18
	const ROUTE_41          ; 19
	const CIANWOOD_CITY     ; 1a
	const CLIFFS_EDGE_GATE  ; 1b
	const ROUTE_47          ; 1c
	const CLIFF_CAVE        ; 1d
	const EMBEDDED_TOWER    ; 1e
	const ROUTE_48          ; 1f
	const WILD_AREA_OUTSIDE ; 20
	const ROUTE_37          ; 21
	const ROUTE_36          ; 22
	const NATIONAL_PARK     ; 23
	const ROUTE_35          ; 24
	const GOLDENROD_CITY    ; 25
	const RADIO_TOWER       ; 26
	const ROUTE_34          ; 27
	const ILEX_FOREST       ; 28
	const AZALEA_TOWN       ; 29
	const SLOWPOKE_WELL     ; 2a
	const ROUTE_33          ; 2b
	const UNION_CAVE        ; 2c
	const ROUTE_32          ; 2d
	const RUINS_OF_ALPH     ; 2e
	const VIOLET_CITY       ; 2f
	const SPROUT_TOWER      ; 30
	const ROUTE_31          ; 31
	const ROUTE_30          ; 32
	const CHERRYGROVE_CITY  ; 33
	const ROUTE_29          ; 34
	const NEW_BARK_TOWN     ; 35
	const ROUTE_46          ; 36
	const SILVER_CAVE       ; 37
KANTO_LANDMARK EQU const_value
	const PALLET_TOWN       ; 38
	const ROUTE_1           ; 39
	const VIRIDIAN_CITY     ; 3a
	const ROUTE_2           ; 3b
	const VIRIDIAN_FOREST   ; 3c
	const PEWTER_CITY       ; 3d
	const ROUTE_3           ; 3e
	const MT_MOON           ; 3f
	const ROUTE_4           ; 40
	const CERULEAN_CITY     ; 41
	const CERULEAN_CAVE     ; 42
	const ROUTE_24          ; 43
	const ROUTE_25          ; 44
	const ROUTE_5           ; 45
	const UNDERGROUND_PATH  ; 46
	const ROUTE_6           ; 47
	const VERMILION_CITY    ; 48
	const DIGLETTS_CAVE     ; 49
	const ROUTE_7           ; 4a
	const ROUTE_8           ; 4b
	const ROUTE_9           ; 4c
	const ROCK_TUNNEL       ; 4d
	const ROUTE_10          ; 4e
	const POWER_PLANT       ; 4f
	const LAVENDER_TOWN     ; 50
	const LAV_RADIO_TOWER   ; 51
	const CELADON_CITY      ; 52
	const SAFFRON_CITY      ; 53
	const ROUTE_11          ; 54
	const ROUTE_12          ; 55
	const ROUTE_13          ; 56
	const ROUTE_14          ; 57
	const ROUTE_15          ; 58
	const ROUTE_16          ; 59
	const ROUTE_17          ; 5a
	const ROUTE_18          ; 5b
	const FUCHSIA_CITY      ; 5c
	const ROUTE_19          ; 5d
	const ROUTE_20          ; 5e
	const SEAFOAM_ISLANDS   ; 5f
	const CINNABAR_ISLAND   ; 60
	const POKEMON_MANSION   ; 61
	const CINNABAR_VOLCANO  ; 62
	const UNKNOWN_2         ; 63
	const ROUTE_21          ; 64
	const ROUTE_22          ; 65
	const VICTORY_ROAD      ; 66
	const ROUTE_23          ; 67
	const INDIGO_PLATEAU    ; 68
	const ROUTE_26          ; 69
	const ROUTE_27          ; 6a
	const TOHJO_FALLS       ; 6b
	const ROUTE_28          ; 6c
SEVII_LANDMARK EQU const_value
	const ONE_ISLAND        ; 6d
	const TREASURE_BEACH    ; 6e
	const KINDLE_ROAD       ; 6f
	const MT_EMBER          ; 70
	const TWO_ISLAND        ; 71
	const CAPE_BRINK        ; 72
	const THREE_ISLAND      ; 73
	const BOND_BRIDGE       ; 74
	const BERRY_FOREST      ; 75
	const FOUR_ISLAND       ; 76
	const ICEFALL_CAVE      ; 77
	const FIVE_ISLAND       ; 78
	const WATER_LABYRINTH   ; 79
	const RESORT_GORGEOUS   ; 7a
	const LOST_CAVE         ; 7b
	const FIVE_ISLE_MEADOW  ; 7c
	const MEMORIAL_ISLAND   ; 7d
	const SIX_ISLAND        ; 7e
	const WATER_PATH        ; 7f
	const GREEN_PATH        ; 80
	const OUTCAST_ISLAND    ; 81
	const ALTERING_CAVE     ; 82
	const RUIN_VALLEY       ; 83
	const DOTTED_HOLE       ; 84
	const SEVEN_ISLAND      ; 85
	const SEVAULT_CANYON    ; 86
	const TANOBI_RUINS      ; 87
	const SACRED_PATH       ; 88
	const ONAGAN_TEMPLE     ; 89

; used in CaughtData
GIFT_LOCATION  EQU $fd
EVENT_LOCATION EQU $fe

; Regions
	const_def
	const JOHTO_REGION  ; 0
	const KANTO_REGION  ; 1
	const SEVII_ISLANDS ; 2
NUM_REGIONS EQU const_value
