; mart types (see engine/items/mart.asm)
	const_def
	const MARTTYPE_STANDARD
	const MARTTYPE_BITTER
	const MARTTYPE_BARGAIN
	const MARTTYPE_PHARMACY
	const MARTTYPE_ROOFTOP
	const MARTTYPE_SHADY
	const MARTTYPE_TMS
	const MARTTYPE_BALLS

; Marts indexes (see data/items/marts.asm)
	const_def
	const MART_CHERRYGROVE
	const MART_VIOLET
	const MART_AZALEA
	const MART_CIANWOOD
	const MART_GOLDENROD_2F_1
	const MART_GOLDENROD_2F_2
	const MART_GOLDENROD_3F
	const MART_GOLDENROD_4F
	const MART_GOLDENROD_5F
	const MART_GOLDENROD_BLACK_MARKET_1
	const MART_GOLDENROD_BLACK_MARKET_2
	const MART_GOLDENROD_BLACK_MARKET_3
	const MART_GOLDENROD_BLACK_MARKET_4
	const MART_OLIVINE
	const MART_ECRUTEAK
	const MART_MAHOGANY_1
	const MART_MAHOGANY_2
	const MART_BLACKTHORN
	const MART_BLACKTHORN_JOURNAL
	const MART_VIRIDIAN
	const MART_PEWTER
	const MART_CERULEAN
	const MART_LAVENDER
	const MART_VERMILION
	const MART_CELADON_2F_1
	const MART_CELADON_2F_2
	const MART_CELADON_3F
	const MART_CELADON_4F
	const MART_CELADON_5F_1
	const MART_CELADON_5F_2
	const MART_FUCHSIA
	const MART_SAFFRON
	const MART_MT_MOON
	const MART_INDIGO_PLATEAU
	const MART_UNDERGROUND
	const MART_WILD_AREA
	const MART_ECRUTEAK_BALLS
	const MART_OLIVINE_TMS
	const MART_BLACKTHORN_TMS
	const MART_AZALEA_TMS
	const MART_VIOLET_TMS
	const MART_LAKE_OF_RAGE
