; StdScripts indexes (see engine/events/std_scripts.asm)
; also used in TileCollisionStdScripts (see data/events/collision_stdscripts.asm)
	enum_start
	enum pokecenternurse
	enum difficultbookshelf
	enum picturebookshelf
	enum magazinebookshelf
	enum incenseburner
	enum merchandiseshelf
	enum townmap
	enum window
	enum tv
	enum homepage
	enum radio1
	enum radio2
	enum trashcan
	enum strengthboulder
	enum smashrock
	enum pokecentersign
	enum martsign
	enum goldenrodrockets
	enum elevatorbutton
	enum daytotext
	enum initializeevents
	enum gymstatue1
	enum gymstatue2
	enum receiveitem
	enum receivetogepiegg
	enum pcscript
	enum gamecornercoinvendor
	enum happinesschecknpc
	enum gymstatue3
	enum gymstatue4
	enum ninjahideoutclear
	enum staticpokemonrefresh
	enum swarmscript
	enum gymstatue5
	enum genericsink
	enum shinypasswordcheck
	enum shinygiftpokemon
