UnknownScript_0xa0aa5:
	sjump PhoneScript_HangupText_Female

UnknownScript_0xa0aad:
	sjump PhoneScript_HangupText_Male

UnknownScript_0xa0ab5:
	sjump PhoneScript_HangupText_Male

UnknownScript_0xa0abd:
	sjump PhoneScript_HangupText_Female

UnknownScript_0xa0ac5:
	sjump PhoneScript_HangupText_Male

UnknownScript_0xa0acd:
	sjump PhoneScript_HangupText_Female

UnknownScript_0xa0ad5:
	sjump PhoneScript_HangupText_Male

UnknownScript_0xa0add:
	sjump PhoneScript_HangupText_Male

UnknownScript_0xa0ae5:
	sjump PhoneScript_HangupText_Female

WiltonWantThis:
	sjump PhoneScript_HangupText_Male
