BitmasksPointers:
	dw BulbasaurBitmasks
	dw IvysaurBitmasks
	dw VenusaurBitmasks
	dw CharmanderBitmasks
	dw CharmeleonBitmasks
	dw CharizardBitmasks
	dw SquirtleBitmasks
	dw WartortleBitmasks
	dw BlastoiseBitmasks
	dw CaterpieBitmasks
	dw MetapodBitmasks
	dw ButterfreeBitmasks
	dw WeedleBitmasks
	dw KakunaBitmasks
	dw BeedrillBitmasks
	dw PidgeyBitmasks
	dw PidgeottoBitmasks
	dw PidgeotBitmasks
	dw RattataBitmasks
	dw RattataABitmasks
	dw RaticateBitmasks
	dw RaticateABitmasks
	dw SpearowBitmasks
	dw FearowBitmasks
	dw EkansBitmasks
	dw ArbokBitmasks
	dw PichuBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw RaichuABitmasks
	dw SandshrewBitmasks
	dw SandshrewABitmasks
	dw SandslashBitmasks
	dw SandslashABitmasks
	dw NidoranFBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw NidoranMBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw CleffaBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw VulpixBitmasks
	dw VulpixABitmasks
	dw NinetalesBitmasks
	dw NinetalesABitmasks
	dw IgglybuffBitmasks
	dw JigglypuffBitmasks
	dw WigglytuffBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw CrobatBitmasks
	dw OddishBitmasks
	dw GloomBitmasks
	dw VileplumeBitmasks
	dw BellossomBitmasks
	dw ParasBitmasks
	dw ParasectBitmasks
	dw VenonatBitmasks
	dw VenomothBitmasks
	dw DiglettBitmasks
	dw DiglettABitmasks
	dw DugtrioBitmasks
	dw DugtrioABitmasks
	dw MeowthBitmasks
	dw MeowthABitmasks
	dw MeowthGBitmasks
	dw PersianBitmasks
	dw PersianABitmasks
	dw PerrserkerBitmasks
	dw PsyduckBitmasks
	dw GolduckBitmasks
	dw MankeyBitmasks
	dw PrimeapeBitmasks
	dw AnnihilapeBitmasks
	dw GrowlitheBitmasks
	dw GrowlitheHBitmasks
	dw ArcanineBitmasks
	dw ArcanineHBitmasks
	dw PoliwagBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw PolitoedBitmasks
	dw AbraBitmasks
	dw KadabraBitmasks
	dw AlakazamBitmasks
	dw MachopBitmasks
	dw MachokeBitmasks
	dw MachampBitmasks
	dw BellsproutBitmasks
	dw WeepinbellBitmasks
	dw VictreebelBitmasks
	dw TentacoolBitmasks
	dw TentacruelBitmasks
	dw GeodudeBitmasks
	dw GeodudeABitmasks
	dw GravelerBitmasks
	dw GravelerABitmasks
	dw GolemBitmasks
	dw GolemABitmasks
	dw PonytaBitmasks
	dw PonytaGBitmasks
	dw RapidashBitmasks
	dw RapidashGBitmasks
	dw SlowpokeBitmasks
	dw SlowpokeGBitmasks
	dw SlowbroBitmasks
	dw SlowbroGBitmasks
	dw SlowkingBitmasks
	dw SlowkingGBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw MagnezoneBitmasks
	dw FarfetchDBitmasks
	dw FarfetchDGBitmasks
	dw SirfetchDBitmasks
	dw DoduoBitmasks
	dw DodrioBitmasks
	dw SeelBitmasks
	dw DewgongBitmasks
	dw GrimerBitmasks
	dw GrimerABitmasks
	dw MukBitmasks
	dw MukABitmasks
	dw ShellderBitmasks
	dw CloysterBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw OnixBitmasks
	dw SteelixBitmasks
	dw DrowzeeBitmasks
	dw HypnoBitmasks
	dw KrabbyBitmasks
	dw KinglerBitmasks
	dw VoltorbBitmasks
	dw VoltorbHBitmasks
	dw ElectrodeBitmasks
	dw ElectrodeHBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorBitmasks
	dw ExeggutorABitmasks
	dw CuboneBitmasks
	dw MarowakBitmasks
	dw MarowakABitmasks
	dw TyrogueBitmasks
	dw HitmonleeBitmasks
	dw HitmonchanBitmasks
	dw HitmontopBitmasks
	dw LickitungBitmasks
	dw LickilickyBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw WeezingGBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw RhyperiorBitmasks
	dw HappinyBitmasks
	dw ChanseyBitmasks
	dw BlisseyBitmasks
	dw TangelaBitmasks
	dw TangrowthBitmasks
	dw KangaskhanBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw KingdraBitmasks
	dw GoldeenBitmasks
	dw SeakingBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw MimeJrBitmasks
	dw MrMimeBitmasks
	dw MrMimeGBitmasks
	dw MrRimeBitmasks
	dw ScytherBitmasks
	dw ScizorBitmasks
	dw KleavorBitmasks
	dw SmoochumBitmasks
	dw JynxBitmasks
	dw ElekidBitmasks
	dw ElectabuzzBitmasks
	dw ElectivireBitmasks
	dw MagbyBitmasks
	dw MagmarBitmasks
	dw MagmortarBitmasks
	dw PinsirBitmasks
	dw TaurosBitmasks
	dw TaurosPBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw LeafeonBitmasks
	dw GlaceonBitmasks
	dw SylveonBitmasks
	dw PorygonBitmasks
	dw Porygon2Bitmasks
	dw PorygonZBitmasks
	dw OmanyteBitmasks
	dw OmastarBitmasks
	dw KabutoBitmasks
	dw KabutopsBitmasks
	dw AerodactylBitmasks
	dw MunchlaxBitmasks
	dw SnorlaxBitmasks
	dw ArticunoBitmasks
	dw ArticunoGBitmasks
	dw ZapdosBitmasks
	dw ZapdosGBitmasks
	dw MoltresBitmasks
	dw MoltresGBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw MewtwoBitmasks
	dw MewBitmasks
	dw ChikoritaBitmasks
	dw BayleefBitmasks
	dw MeganiumBitmasks
	dw CyndaquilBitmasks
	dw QuilavaBitmasks
	dw TyphlosionBitmasks
	dw TyphlosionHBitmasks
	dw TotodileBitmasks
	dw CroconawBitmasks
	dw FeraligatrBitmasks
	dw SentretBitmasks
	dw FurretBitmasks
	dw HoothootBitmasks
	dw NoctowlBitmasks
	dw LedybaBitmasks
	dw LedianBitmasks
	dw SpinarakBitmasks
	dw AriadosBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw TogekissBitmasks
	dw NatuBitmasks
	dw XatuBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw AzurillBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw BonslyBitmasks
	dw SudowoodoBitmasks
	dw HoppipBitmasks
	dw SkiploomBitmasks
	dw JumpluffBitmasks
	dw AipomBitmasks
	dw AmbipomBitmasks
	dw SunkernBitmasks
	dw SunfloraBitmasks
	dw YanmaBitmasks
	dw YanmegaBitmasks
	dw WooperBitmasks
	dw WooperPBitmasks
	dw QuagsireBitmasks
	dw ClodsireBitmasks
	dw MurkrowBitmasks
	dw HonchkrowBitmasks
	dw MisdreavusBitmasks
	dw MismagiusBitmasks
	dw UnownBitmasks
	dw WynautBitmasks
	dw WobbuffetBitmasks
	dw GirafarigBitmasks
	dw FarigirafBitmasks
	dw PinecoBitmasks
	dw ForretressBitmasks
	dw DunsparceBitmasks
	dw DudunsparsBitmasks
	dw GligarBitmasks
	dw GliscorBitmasks
	dw SnubbullBitmasks
	dw GranbullBitmasks
	dw QwilfishBitmasks
	dw OverqwilBitmasks
	dw ShuckleBitmasks
	dw HeracrossBitmasks
	dw SneaselBitmasks
	dw SneaselHBitmasks
	dw WeavileBitmasks
	dw SneaslerBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw UrsalunaBitmasks
	dw SlugmaBitmasks
	dw MagcargoBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw MamoswineBitmasks
	dw CorsolaJBitmasks
	dw CorsolaBitmasks
	dw CursolaBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw DelibirdBitmasks
	dw MantykeBitmasks
	dw MantineBitmasks
	dw SkarminiBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw StantlerBitmasks
	dw WyrdeerBitmasks
	dw SmeargleBitmasks
	dw MiltankBitmasks
	dw KotoraBitmasks
	dw RaitoraBitmasks
	dw GorotoraBitmasks
	dw BudewBitmasks
	dw RoseliaBitmasks
	dw RoseradeBitmasks
	dw ElectrikeBitmasks
	dw ManectricBitmasks
	dw CroagunkBitmasks
	dw ToxicroakBitmasks
	dw SwabluBitmasks
	dw AltariaBitmasks
	dw DuskullBitmasks
	dw DusclopsBitmasks
	dw DusknoirBitmasks
	dw LotadBitmasks
	dw LombreBitmasks
	dw LudicoloBitmasks
	dw SnoruntBitmasks
	dw GlalieBitmasks
	dw FroslassBitmasks
	dw BronzorBitmasks
	dw BronzongBitmasks
	dw CacneaBitmasks
	dw CacturneBitmasks
	dw RaltsBitmasks
	dw KirliaBitmasks
	dw GardevoirBitmasks
	dw GalladeBitmasks
	dw ShroomishBitmasks
	dw BreloomBitmasks
	dw AronBitmasks
	dw LaironBitmasks
	dw AggronBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw GibleBitmasks
	dw GabiteBitmasks
	dw GarchompBitmasks
	dw BagonBitmasks
	dw ShelgonBitmasks
	dw SalamenceBitmasks
	dw BeldumBitmasks
	dw MetangBitmasks
	dw MetagrossBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
	dw NownBitmasks
	dw MissingnoBitmasks
	dw RegirockBitmasks
	dw RegiceBitmasks
	dw RegisteelBitmasks
	dw RegielekiBitmasks
	dw RegidragoBitmasks
	dw RegigigasBitmasks
	dw DeoxysBitmasks
	dw TaurosPFireBitmasks
	dw TaurosPWaterBitmasks
