NewFrames:

MetagrossFrames:  INCLUDE "gfx/pokemon/metagross/frames.asm"
LugiaFrames:      INCLUDE "gfx/pokemon/lugia/frames.asm"
HoOhFrames:       INCLUDE "gfx/pokemon/ho_oh/frames.asm"
CelebiFrames:     INCLUDE "gfx/pokemon/celebi/frames.asm"
MissingnoFrames:  INCLUDE "gfx/pokemon/missingno/frames.asm"
NownFrames:       INCLUDE "gfx/pokemon/nown/frames.asm"
RegirockFrames:   INCLUDE "gfx/pokemon/regirock/frames.asm"
RegiceFrames:     INCLUDE "gfx/pokemon/regice/frames.asm"
RegisteelFrames:  INCLUDE "gfx/pokemon/registeel/frames.asm"
RegielekiFrames:  INCLUDE "gfx/pokemon/regieleki/frames.asm"
RegidragoFrames:  INCLUDE "gfx/pokemon/regidrago/frames.asm"
RegigigasFrames:  INCLUDE "gfx/pokemon/regigigas/frames.asm"
DeoxysFrames:     INCLUDE "gfx/pokemon/deoxys/frames.asm"
TaurosPFireFrames: INCLUDE "gfx/pokemon/tauros_p_fire/frames.asm"
TaurosPWaterFrames: INCLUDE "gfx/pokemon/tauros_p_water/frames.asm"
EggFrames:        INCLUDE "gfx/pokemon/egg/frames.asm"