SECTION "Effect Commands", ROMX

INCLUDE "engine/battle/effect_commands.asm"

INCLUDE "data/moves/critical_hit_moves.asm"
INCLUDE "data/battle/critical_hit_chances.asm"
INCLUDE "engine/battle/ai/switch.asm"
INCLUDE "data/types/type_matchups.asm"
INCLUDE "data/battle/accuracy_multipliers.asm"
INCLUDE "data/types/type_boost_items.asm"
INCLUDE "engine/battle/move_effects/counter.asm"
INCLUDE "engine/battle/move_effects/pain_split.asm"
INCLUDE "engine/battle/move_effects/sleep_talk.asm"
INCLUDE "engine/battle/move_effects/destiny_bond.asm"
INCLUDE "engine/battle/move_effects/spite.asm"
INCLUDE "engine/battle/move_effects/mist.asm"
INCLUDE "engine/battle/move_effects/heal_bell.asm"
INCLUDE "engine/battle/move_effects/u_turn.asm"
INCLUDE "engine/battle/move_effects/sketch.asm"

SECTION "Effect Commands Extra", ROMX
INCLUDE "engine/battle/effect_commands_extra.asm"

INCLUDE "engine/battle/move_effects/acrobatics.asm"
INCLUDE "engine/battle/move_effects/knock_off.asm"
INCLUDE "engine/battle/move_effects/hex.asm"
INCLUDE "engine/battle/move_effects/false_swipe.asm"
INCLUDE "engine/battle/move_effects/fury_cutter.asm"
INCLUDE "engine/battle/move_effects/thief.asm"
INCLUDE "engine/battle/move_effects/triple_kick.asm"
INCLUDE "data/moves/flail_reversal_power.asm"
INCLUDE "engine/battle/move_effects/lock_on.asm"
INCLUDE "engine/battle/move_effects/snore.asm"
INCLUDE "engine/battle/move_effects/encore.asm"
INCLUDE "engine/battle/move_effects/brick_break.asm"
INCLUDE "engine/battle/move_effects/roost.asm"
